In [190]:
import pandas as pd

# Example nested JSON structure for Tarif
tarif = {
    "Netznutzung": {
        "winter": {
            "mo-fri": {
                "0": 9.40, "1": 9.40, "2": 9.40, "3": 9.40, "4": 9.40, "5": 9.40, "6": 13.55, "7": 13.55, "8": 13.55, "9": 13.55, "10": 13.55, "11": 13.55, "12": 13.55, "13": 13.55,
                "14": 13.55, "15": 13.55, "16": 13.55, "17": 13.55, "18": 13.55, "19": 13.55,
                "20": 13.55, "21": 9.40, "22": 9.40, "23": 9.40
            },
            "sa": {
                "0": 9.40, "1": 9.40, "2": 9.40, "3": 9.40, "4": 9.40, "5": 9.40, "6": 9.40,
                "7": 9.40, "8": 9.40, "9": 9.40, "10": 9.40, "11": 9.40, "12": 9.40, "13": 9.40,
                "14": 9.40, "15": 9.40, "16": 9.40, "17": 9.40, "18": 9.40, "19": 9.40,
                "20": 9.40, "21": 9.40, "22": 9.40, "23": 9.40
            },
            "su": {
                "0": 9.40, "1": 9.40, "2": 9.40, "3": 9.40, "4": 9.40, "5": 9.40, "6": 9.40,
                "7": 9.40, "8": 9.40, "9": 9.40, "10": 9.40, "11": 9.40, "12": 9.40, "13": 9.40,
                "14": 9.40, "15": 9.40, "16": 9.40, "17": 9.40, "18": 9.40, "19": 9.40,
                "20": 9.40, "21": 9.40, "22": 9.40, "23": 9.40
            }
        },
        "sommer": {
            "mo-fri": {
                "0": 9.40, "1": 9.40, "2": 9.40, "3": 9.40, "4": 9.40, "5": 9.40, "6": 13.55, "7": 13.55, "8": 13.55, "9": 13.55, "10": 13.55, "11": 13.55, "12": 13.55, "13": 13.55,
                "14": 13.55, "15": 13.55, "16": 13.55, "17": 13.55, "18": 13.55, "19": 13.55,
                "20": 13.55, "21": 9.40, "22": 9.40, "23": 9.40
            },
            "sa": {
                "0": 9.40, "1": 9.40, "2": 9.40, "3": 9.40, "4": 9.40, "5": 9.40, "6": 9.40,
                "7": 9.40, "8": 9.40, "9": 9.40, "10": 9.40, "11": 9.40, "12": 9.40, "13": 9.40,
                "14": 9.40, "15": 9.40, "16": 9.40, "17": 9.40, "18": 9.40, "19": 9.40,
                "20": 9.40, "21": 9.40, "22": 9.40, "23": 9.40
            },
            "su": {
                "0": 9.40, "1": 9.40, "2": 9.40, "3": 9.40, "4": 9.40, "5": 9.40, "6": 9.40,
                "7": 9.40, "8": 9.40, "9": 9.40, "10": 9.40, "11": 9.40, "12": 9.40, "13": 9.40,
                "14": 9.40, "15": 9.40, "16": 9.40, "17": 9.40, "18": 9.40, "19": 9.40,
                "20": 9.40, "21": 9.40, "22": 9.40, "23": 9.40
            }
        }
    },
    "Energielieferung": {
        "winter": {
            "mo-fri": {
                "0": 10.10, "1": 10.10, "2": 10.10, "3": 10.10, "4": 10.10, "5": 10.10, "6": 13.25, "7": 13.25, "8": 13.25, "9": 13.25, "10": 13.25, "11": 13.25, "12": 13.25, "13": 13.25,
                "14": 13.25, "15": 13.25, "16": 13.25, "17": 13.25, "18": 13.25, "19": 13.25,
                "20": 13.25, "21": 10.10, "22": 10.10, "23": 10.10
            },
            "sa": {
                "0": 10.10, "1": 10.10, "2": 10.10, "3": 10.10, "4": 10.10, "5": 10.10, "6": 10.10,
                "7": 10.10, "8": 10.10, "9": 10.10, "10": 10.10, "11":10.10, "12": 10.10, "13": 10.10,
                "14": 10.10, "15": 10.10, "16": 10.10, "17": 10.10, "18": 10.10, "19": 10.10,
                "20": 10.10, "21": 10.10, "22": 10.10, "23": 10.10
            },
            "su": {
                "0": 10.10, "1": 10.10, "2": 10.10, "3": 10.10, "4": 10.10, "5": 10.10, "6": 10.10,
                "7": 10.10, "8": 10.10, "9": 10.10, "10": 10.10, "11":10.10, "12": 10.10, "13": 10.10,
                "14": 10.10, "15": 10.10, "16": 10.10, "17": 10.10, "18": 10.10, "19": 10.10,
                "20": 10.10, "21": 10.10, "22": 10.10, "23": 10.10
            }
        },
        "sommer": {
            "mo-fri": {
                "0": 10.10, "1": 10.10, "2": 10.10, "3": 10.10, "4": 10.10, "5": 10.10, "6": 13.25, "7": 13.25, "8": 13.25, "9": 13.25, "10": 13.25, "11": 13.25, "12": 13.25, "13": 13.25,
                "14": 13.25, "15": 13.25, "16": 13.25, "17": 13.25, "18": 13.25, "19": 13.25,
                "20": 13.25, "21": 10.10, "22": 10.10, "23": 10.10
            },
            "sa": {
                "0": 10.10, "1": 10.10, "2": 10.10, "3": 10.10, "4": 10.10, "5": 10.10, "6": 10.10,
                "7": 10.10, "8": 10.10, "9": 10.10, "10": 10.10, "11":10.10, "12": 10.10, "13": 10.10,
                "14": 10.10, "15": 10.10, "16": 10.10, "17": 10.10, "18": 10.10, "19": 10.10,
                "20": 10.10, "21": 10.10, "22": 10.10, "23": 10.10
            },
            "su": {
                "0": 10.10, "1": 10.10, "2": 10.10, "3": 10.10, "4": 10.10, "5": 10.10, "6": 10.10,
                "7": 10.10, "8": 10.10, "9": 10.10, "10": 10.10, "11":10.10, "12": 10.10, "13": 10.10,
                "14": 10.10, "15": 10.10, "16": 10.10, "17": 10.10, "18": 10.10, "19": 10.10,
                "20": 10.10, "21": 10.10, "22": 10.10, "23": 10.10
            }
        }
    }
}

# Step 2: Extract the data
data = []
for category, seasons in tarif.items():
    for season, days in seasons.items():
        for day, hours in days.items():
            for hour, value in hours.items():
                data.append({
                    "Category": category,
                    "Season": season,
                    "Day": day,
                    "Hour": hour,
                    "Value": value
                })
df = pd.DataFrame(data)
df

             Category  Season     Day Hour  Value
0         Netznutzung  winter  mo-fri    0    9.4
1         Netznutzung  winter  mo-fri    1    9.4
2         Netznutzung  winter  mo-fri    2    9.4
3         Netznutzung  winter  mo-fri    3    9.4
4         Netznutzung  winter  mo-fri    4    9.4
..                ...     ...     ...  ...    ...
283  Energielieferung  sommer      su   19   10.1
284  Energielieferung  sommer      su   20   10.1
285  Energielieferung  sommer      su   21   10.1
286  Energielieferung  sommer      su   22   10.1
287  Energielieferung  sommer      su   23   10.1

[288 rows x 5 columns]

In [223]:
# Example nested JSON 
durchschnittpreis = {
    "Netznutzung": {
        "grundpreis": 120,
        "leistungspreis": 0,
        "systemdienstleistung": 0.75, 
        "additional_rabatt": 0
    },
    "Energielieferung": {
        "grundpreis": 59,
        "leistungspreis": 0,
        "additional_rabatt": 0
    },
    "Abgaben": [0.34],
    "Netzuschlag": 2.30
}   


flattened_data = []
for key, value in durchschnittpreis.items():
    if isinstance(value, dict):
        for sub_key, sub_value in value.items():
            flattened_data.append({"Category": key, "Type": sub_key, "Value": sub_value})
    elif isinstance(value, list):
        for i, item in enumerate(value):
            flattened_data.append({"Category": key, "Type": f"value_{i+1}", "Value": item})
    else:
        flattened_data.append({"Category": key, "Type": "value", "Value": value})

durch_df = pd.DataFrame(flattened_data)

# Display DataFrame
print(durch_df)

           Category                  Type   Value
0       Netznutzung            grundpreis  120.00
1       Netznutzung        leistungspreis    0.00
2       Netznutzung  systemdienstleistung    0.75
3       Netznutzung     additional_rabatt    0.00
4  Energielieferung            grundpreis   59.00
5  Energielieferung        leistungspreis    0.00
6  Energielieferung     additional_rabatt    0.00
7           Abgaben               value_1    0.34
8  Gemeinde_abgaben               value_1    0.00
9       Netzuschlag                 value    2.30

In [221]:
def durchschnitt_calculation(durchscnitt_df, tariff_df):
    #calculation for Netznutzung
    seasonal_netz_df = get_seasonal_averages(tariff_df, "Netz")
    avg_netz = get_yearly_average_tarif(seasonal_netz_df)
    durch_netz = durchscnitt_df[durchscnitt_df["Category"] == "Netznutzung"].copy().drop(["Category"], axis=1)
    durch_netz.set_index("Type", inplace=True)
    total_netz = ((durch_netz.loc["grundpreis"].Value+durch_netz.loc["leistungspreis"].Value)*100/TOT_VERBRAUCH_H4) + durch_netz.loc["systemdienstleistung"].Value + avg_netz-durch_netz.loc["additional_rabatt"].Value
    
    #calculation for Energielieferung
    seasonal_ener_df = get_seasonal_averages(tariff_df, "Energie")
    avg_ener = get_yearly_average_tarif(seasonal_ener_df)
    durch_ener = durchscnitt_df[durchscnitt_df["Category"] == "Energielieferung"].copy().drop(["Category"], axis=1)
    durch_ener.set_index("Type", inplace=True)
    total_ener = ((durch_ener.loc["grundpreis"].Value+durch_ener.loc["leistungspreis"].Value)*100/TOT_VERBRAUCH_H4) + avg_ener - durch_ener.loc["additional_rabatt"].Value
    
    #calculation Gemeinde Abgaben
    abgaben_max = durchscnitt_df[durchscnitt_df["Category"]=="Abgaben"].Value.max()
    abgaben_min = durchscnitt_df[durchscnitt_df["Category"]=="Abgaben"].Value.min()

    
    #Netzzuschlag
    netzzuschlag = durchscnitt_df[durchscnitt_df["Category"]=="Netzuschlag"].Value
    
    total_duschschnitt_min = total_netz + total_ener + abgaben_min + netzzuschlag
    total_duschschnitt_max = total_netz + total_ener + abgaben_max + netzzuschlag
    return total_duschschnitt_min, total_duschschnitt_max

In [222]:
durchschnitt_calculation(durch_df, example)

(9    30.454206
 Name: Value, dtype: float64,
 9    30.674206
 Name: Value, dtype: float64)

In [118]:
h4_verbrauch_df = pd.read_csv("data/hourly_verbrauch_h4.csv")

In [193]:
df['Hour'] = df['Hour'].astype(int) 
example = pd.merge(df, h4_verbrauch_df, on=["Season", "Hour"], how="left")

In [120]:
example_n = example.query("Category=='Netznutzung'")

In [121]:
example_n

        Category  Season     Day  Hour  Value  Verbrauch
0    Netznutzung  winter  mo-fri     0    9.4        500
1    Netznutzung  winter  mo-fri     1    9.4        500
2    Netznutzung  winter  mo-fri     2    9.4        500
3    Netznutzung  winter  mo-fri     3    9.4        500
4    Netznutzung  winter  mo-fri     4    9.4        500
..           ...     ...     ...   ...    ...        ...
139  Netznutzung  sommer      su    19    9.4        500
140  Netznutzung  sommer      su    20    9.4        500
141  Netznutzung  sommer      su    21    9.4        500
142  Netznutzung  sommer      su    22    9.4        440
143  Netznutzung  sommer      su    23    9.4        440

[144 rows x 6 columns]

In [122]:
period1 = example_n[(example_n['Hour']>=6) & (example_n['Hour']<12)]
period1

        Category  Season     Day  Hour  Value  Verbrauch
6    Netznutzung  winter  mo-fri     6  13.55        690
7    Netznutzung  winter  mo-fri     7  13.55        690
8    Netznutzung  winter  mo-fri     8  13.55        690
9    Netznutzung  winter  mo-fri     9  13.55        690
10   Netznutzung  winter  mo-fri    10  13.55        690
11   Netznutzung  winter  mo-fri    11  13.55        690
30   Netznutzung  winter      sa     6   9.40        690
31   Netznutzung  winter      sa     7   9.40        690
32   Netznutzung  winter      sa     8   9.40        690
33   Netznutzung  winter      sa     9   9.40        690
34   Netznutzung  winter      sa    10   9.40        690
35   Netznutzung  winter      sa    11   9.40        690
54   Netznutzung  winter      su     6   9.40        690
55   Netznutzung  winter      su     7   9.40        690
56   Netznutzung  winter      su     8   9.40        690
57   Netznutzung  winter      su     9   9.40        690
58   Netznutzung  winter      su    10   9.40        690
59   Netznutzung  winter      su    11   9.40        690
78   Netznutzung  sommer  mo-fri     6  13.55        600
79   Netznutzung  sommer  mo-fri     7  13.55        600
80   Netznutzung  sommer  mo-fri     8  13.55        600
81   Netznutzung  sommer  mo-fri     9  13.55        600
82   Netznutzung  sommer  mo-fri    10  13.55        600
83   Netznutzung  sommer  mo-fri    11  13.55        600
102  Netznutzung  sommer      sa     6   9.40        600
103  Netznutzung  sommer      sa     7   9.40        600
104  Netznutzung  sommer      sa     8   9.40        600
105  Netznutzung  sommer      sa     9   9.40        600
106  Netznutzung  sommer      sa    10   9.40        600
107  Netznutzung  sommer      sa    11   9.40        600
126  Netznutzung  sommer      su     6   9.40        600
127  Netznutzung  sommer      su     7   9.40        600
128  Netznutzung  sommer      su     8   9.40        600
129  Netznutzung  sommer      su     9   9.40        600
130  Netznutzung  sommer      su    10   9.40        600
131  Netznutzung  sommer      su    11   9.40        600

In [123]:
period1.groupby(['Category', 'Season', 'Day'], as_index = False).mean()

      Category  Season     Day  Hour  Value  Verbrauch
0  Netznutzung  sommer  mo-fri   8.5  13.55      600.0
1  Netznutzung  sommer      sa   8.5   9.40      600.0
2  Netznutzung  sommer      su   8.5   9.40      600.0
3  Netznutzung  winter  mo-fri   8.5  13.55      690.0
4  Netznutzung  winter      sa   8.5   9.40      690.0
5  Netznutzung  winter      su   8.5   9.40      690.0

In [124]:
def average_on_day_period(df):
    weekly_mean_df = df.groupby(['Category', 'Season', 'Day'], as_index = False).mean()
    for index, row in weekly_mean_df.iterrows():
        if row['Day'] == 'mo-fri':
            weekly_mean_df.loc[index, 'Value'] = row['Value']*5*row['Verbrauch']/(7*100)
        else:
            weekly_mean_df.loc[index, 'Value'] = row['Value']*row['Verbrauch']/(7*100)
    weekly_mean_df.drop(['Category', 'Day', 'Verbrauch', 'Hour'], axis = 1, inplace = True)
    weekly_mean_df.reset_index(drop=True, inplace=True)
    return weekly_mean_df.groupby(['Season'], as_index = False).sum()

In [125]:
average_on_day_period(period1)

   Season      Value
0  sommer  74.185714
1  winter  85.313571

In [185]:
#this function splits the big df in periods, applies iteratively the weekly means for each period and returns a big dataframe with all averages for each season for each period

def get_seasonal_averages(example, category):
    if category not in ['Netz', 'Energie']:
        raise ValueError("Invalid option. Expected 'Netz' or 'Energie'.")
    if category == 'Netz':
        df = example.query("Category=='Netznutzung'")
    else:
        df = example.query("Category=='Energielieferung'")

    # The dataframe is splitted in the periods defined by Elcom
    period1_df = df[(df['Hour']>=6) & (df['Hour']<12)].copy()
    period2_df = df[(df['Hour']>=12) & (df['Hour']<18)].copy()
    period3_df = df[(df['Hour']>=18) & (df['Hour']<22)].copy()
    period4_df = df[(df['Hour']>=22) | (df['Hour']<6)].copy()
    periods = [period1_df, period2_df, period3_df, period4_df]
    averages =[]
    for period_df in periods:
        averages.append(average_on_day_period(period_df))
        
    concatenated_df = pd.concat(averages, axis=0, ignore_index=True)
    return concatenated_df

In [186]:
get_seasonal_averages(example, 'Energie')

   Season      Value
0  sommer  74.185714
1  winter  85.313571
2  sommer  66.767143
3  winter  77.895000
4  sommer  58.116071
5  winter  69.739286
6  sommer  41.360000
7  winter  47.000000

In [128]:
TOT_VERBRAUCH_H4 = 4500
def get_yearly_average_tarif(seasonal_avg_df):
    total_price = seasonal_avg_df['Value'].sum()
    return total_price/TOT_VERBRAUCH_H4*100

In [194]:
a = get_seasonal_averages(example, 'Energie')
a

   Season    Value
0  sommer  74.1000
1  winter  85.2150
2  sommer  66.6900
3  winter  77.8050
4  sommer  58.9375
5  winter  70.7250
6  sommer  44.4400
7  winter  50.5000

In [195]:
get_yearly_average_tarif(a)

np.float64(11.7425)

In [131]:
b = get_yearly_average_tarif(a)
b

np.float64(11.563928571428574)

In [131]:
def get_df_from_json(json_file):
    return ()

In [249]:
import json
pdf_data = {
    "Netzbetreiber": "Azienda Elettrica Comunale di Bedretto",
    "Produkte": [
        {
            "Name": "Tariffa Primaria",
            "Beschreibung": "Prelievo regolare durante tutto l'anno, Allacciamento alla rete a livello 7",
            "Komponenten": [
                {
                    "Name": "Noleggio Contatore",
                    "Beschreibung": "Costo del noleggio del contatore",
                    "Einheit": "CHF/Monat",
                    "Unterkategorie": "Grundpreis Netz inkl. Messung, Zählermiete, Abrechnung",
                    "Menge": "24.00",
                    "Tariftyp": "Einfachtarif",
                    "Tarifzeiten": "Inverno/Estate"
                },
                {
                    "Name": "Tassa Base",
                    "Beschreibung": "Tassa base per la gestione della rete",
                    "Einheit": "CHF/Monat",
                    "Unterkategorie": "Netznutzung",
                    "Menge": "25.00",
                    "Tariftyp": "Einfachtarif",
                    "Tarifzeiten": "Inverno/Estate"
                },
                {
                    "Name": "Trasporto energia",
                    "Beschreibung": "Costo del trasporto dell'energia",
                    "Einheit": "Rp./kWh",
                    "Unterkategorie": "Netznutzung",
                    "Menge": "10.50",
                    "Tariftyp": "Einfachtarif",
                    "Tarifzeiten": "Inverno/Estate"
                },
                {
                    "Name": "Energia elettrica",
                    "Beschreibung": "Costo dell'energia elettrica",
                    "Einheit": "Rp./kWh",
                    "Unterkategorie": "Energie",
                    "Menge": "9.10",
                    "Tariftyp": "Einfachtarif",
                    "Tarifzeiten": "Inverno/Estate"
                }
            ],
            "Gültigkeit": "2024-01-01",
            "Verbrauchskategorie": "Energie",
            "Verbrauchstyp": "Haushalt",
            "Netzebene": "Niederspannung",
            "Standardprodukt": "Ja"
        }
    ],
    "Netznutzung": {
        "Winter": {
            "Montag-Freitag": {
                "Von 00:00 bis 01:00 in Rp./kWh": 10.50
            },
            "Samstag": {
                "Von 00:00 bis 01:00 in Rp./kWh": 10.50
            },
            "Sonntag": {
                "Von 00:00 bis 01:00 in Rp./kWh": 10.50
            }
        },
        "Sommer": {
            "Montag-Freitag": {
                "Von 00:00 bis 01:00 in Rp./kWh": 10.50
            },
            "Samstag": {
                "Von 00:00 bis 01:00 in Rp./kWh": 10.50
            },
            "Sonntag": {
                "Von 00:00 bis 01:00 in Rp./kWh": 10.50
            }
        }
    },
    "Energielieferung": {
        "Winter": {
            "Montag-Freitag": {
                "Von 00:00 bis 01:00 in Rp./kWh": 9.10
            },
            "Samstag": {
                "Von 00:00 bis 01:00 in Rp./kWh": 9.10,
                "Von 01:00 bis 02:00 in Rp./kWh": 9.12
            },
            "Sonntag": {
                "Von 00:00 bis 01:00 in Rp./kWh": 9.10
            }
        },
        "Sommer": {
            "Montag-Freitag": {
                "Von 00:00 bis 01:00 in Rp./kWh": 9.10
            },
            "Samstag": {
                "Von 00:00 bis 01:00 in Rp./kWh": 9.10
            },
            "Sonntag": {
                "Von 00:00 bis 01:00 in Rp./kWh": 9.10
            }
        }
    },
    "durchschnittpreis" : {
        "Netznutzung": {
            "grundpreis": 120,
            "leistungspreis": 0,
            "systemdienstleistung": 0.75, 
            "additional_rabatt": 0
        },
        "Energielieferung": {
            "grundpreis": 59,
            "leistungspreis": 0,
            "additional_rabatt": 0
        },
    "Abgaben": [0.34],
    "Netzuschlag": 2.30
}  
}

# Writing the data to a JSON file
json_filename = 'data/converted_tarifblatt.json'
with open(json_filename, 'w') as json_file:
    json.dump(pdf_data, json_file, indent=4)

json_filename

'data/converted_tarifblatt.json'

In [250]:
with open(json_filename, 'r') as file:
    input_json = json.load(file)
input_json

{'Netzbetreiber': 'Azienda Elettrica Comunale di Bedretto',
 'Produkte': [{'Name': 'Tariffa Primaria',
   'Beschreibung': "Prelievo regolare durante tutto l'anno, Allacciamento alla rete a livello 7",
   'Komponenten': [{'Name': 'Noleggio Contatore',
     'Beschreibung': 'Costo del noleggio del contatore',
     'Einheit': 'CHF/Monat',
     'Unterkategorie': 'Grundpreis Netz inkl. Messung, Zählermiete, Abrechnung',
     'Menge': '24.00',
     'Tariftyp': 'Einfachtarif',
     'Tarifzeiten': 'Inverno/Estate'},
    {'Name': 'Tassa Base',
     'Beschreibung': 'Tassa base per la gestione della rete',
     'Einheit': 'CHF/Monat',
     'Unterkategorie': 'Netznutzung',
     'Menge': '25.00',
     'Tariftyp': 'Einfachtarif',
     'Tarifzeiten': 'Inverno/Estate'},
    {'Name': 'Trasporto energia',
     'Beschreibung': "Costo del trasporto dell'energia",
     'Einheit': 'Rp./kWh',
     'Unterkategorie': 'Netznutzung',
     'Menge': '10.50',
     'Tariftyp': 'Einfachtarif',
     'Tarifzeiten': 'Inverno/Estate'},
    {'Name': 'Energia elettrica',
     'Beschreibung': "Costo dell'energia elettrica",
     'Einheit': 'Rp./kWh',
     'Unterkategorie': 'Energie',
     'Menge': '9.10',
     'Tariftyp': 'Einfachtarif',
     'Tarifzeiten': 'Inverno/Estate'}],
   'Gültigkeit': '2024-01-01',
   'Verbrauchskategorie': 'Energie',
   'Verbrauchstyp': 'Haushalt',
   'Netzebene': 'Niederspannung',
   'Standardprodukt': 'Ja'}],
 'Netznutzung': {'Winter': {'Montag-Freitag': {'Von 00:00 bis 01:00 in Rp./kWh': 10.5},
   'Samstag': {'Von 00:00 bis 01:00 in Rp./kWh': 10.5},
   'Sonntag': {'Von 00:00 bis 01:00 in Rp./kWh': 10.5}},
  'Sommer': {'Montag-Freitag': {'Von 00:00 bis 01:00 in Rp./kWh': 10.5},
   'Samstag': {'Von 00:00 bis 01:00 in Rp./kWh': 10.5},
   'Sonntag': {'Von 00:00 bis 01:00 in Rp./kWh': 10.5}}},
 'Energielieferung': {'Winter': {'Montag-Freitag': {'Von 00:00 bis 01:00 in Rp./kWh': 9.1},
   'Samstag': {'Von 00:00 bis 01:00 in Rp./kWh': 9.1,
    'Von 01:00 bis 02:00 in Rp./kWh': 9.12},
   'Sonntag': {'Von 00:00 bis 01:00 in Rp./kWh': 9.1}},
  'Sommer': {'Montag-Freitag': {'Von 00:00 bis 01:00 in Rp./kWh': 9.1},
   'Samstag': {'Von 00:00 bis 01:00 in Rp./kWh': 9.1},
   'Sonntag': {'Von 00:00 bis 01:00 in Rp./kWh': 9.1}}},
 'durchschnittpreis': {'Netznutzung': {'grundpreis': 120,
   'leistungspreis': 0,
   'systemdienstleistung': 0.75,
   'additional_rabatt': 0},
  'Energielieferung': {'grundpreis': 59,
   'leistungspreis': 0,
   'additional_rabatt': 0},
  'Abgaben': [0.34],
  'Netzuschlag': 2.3}}

In [246]:
def clean_seasonal_data(df):
    #extract the number of the first hour from string
    def extract_first_hour(s):
        split_string = s.split()
        start_time = split_string[1].split(':')  # Extract the '00' part
        return int(start_time[0])  # Convert the hour part to integer
    df['first_hour'] = df['Hour'].apply(extract_first_hour)
    df.drop(['Hour'], axis=1, inplace=True)
    df.rename(columns = {'first_hour': 'Hour'},inplace=True)
    return df

            Category  Season             Day  Value  Hour
0        Netznutzung  Winter  Montag-Freitag  10.50     0
1        Netznutzung  Winter         Samstag  10.50     0
2        Netznutzung  Winter         Sonntag  10.50     0
3        Netznutzung  Sommer  Montag-Freitag  10.50     0
4        Netznutzung  Sommer         Samstag  10.50     0
5        Netznutzung  Sommer         Sonntag  10.50     0
6   Energielieferung  Winter  Montag-Freitag   9.10     0
7   Energielieferung  Winter         Samstag   9.10     0
8   Energielieferung  Winter         Samstag   9.12     1
9   Energielieferung  Winter         Sonntag   9.10     0
10  Energielieferung  Sommer  Montag-Freitag   9.10     0
11  Energielieferung  Sommer         Samstag   9.10     0
12  Energielieferung  Sommer         Sonntag   9.10     0

In [248]:
def extract_df_seasonal_tariffs(input_json):
    tarif = {'Netznutzung': input_json['Netznutzung'], 'Energielieferung': input_json['Energielieferung']}
    data = []
    for category, seasons in tarif.items():
        for season, days in seasons.items():
            for day, hours in days.items():
                for hour, value in hours.items():
                    data.append({
                        "Category": category,
                        "Season": season,
                        "Day": day,
                        "Hour": hour,
                        "Value": value
                    })
        df = pd.DataFrame(data)
        cleaned_df = clean_seasonal_data(df)            
    return cleaned_df

extract_df_seasonal_tariffs(input_json)

            Category  Season             Day  Value  Hour
0        Netznutzung  Winter  Montag-Freitag  10.50     0
1        Netznutzung  Winter         Samstag  10.50     0
2        Netznutzung  Winter         Sonntag  10.50     0
3        Netznutzung  Sommer  Montag-Freitag  10.50     0
4        Netznutzung  Sommer         Samstag  10.50     0
5        Netznutzung  Sommer         Sonntag  10.50     0
6   Energielieferung  Winter  Montag-Freitag   9.10     0
7   Energielieferung  Winter         Samstag   9.10     0
8   Energielieferung  Winter         Samstag   9.12     1
9   Energielieferung  Winter         Sonntag   9.10     0
10  Energielieferung  Sommer  Montag-Freitag   9.10     0
11  Energielieferung  Sommer         Samstag   9.10     0
12  Energielieferung  Sommer         Sonntag   9.10     0

In [ ]:
def extract_df_seasonal_tariffs(input_json):
    tarif = {'Netznutzung': input_json['Netznutzung'], 'Energielieferung': input_json['Energielieferung']}
    data = []
    for category, seasons in tarif.items():
        for season, days in seasons.items():
            for day, hours in days.items():
                for hour, value in hours.items():
                    data.append({
                        "Category": category,
                        "Season": season,
                        "Day": day,
                        "Hour": hour,
                        "Value": value
                    })
        df = pd.DataFrame(data)
        cleaned_df = clean_seasonal_data(df)            
    return cleaned_df